# -*- coding: utf-8 -*-
"""aplied statics(e1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vnCh7F41ux66NqZIQiiLevs3SVTZZVUK
"""

#exercise 1
import pandas as pd
import numpy as np
info = np.array(["1","2","3","4","%","6"])
a = pd.Series(info)
print(a)

mobile =["nokia","samsung"] # list in string
df=pd.DataFrame(mobile) #calling DataFrame constructor on list
print(df)

language = pd.Series(["Hindi","English", "Math"])
language.map({"Hindi":"language","English":"International laguage"})

#example2
language.map(lambda x: "i like {}".format(x),na_action="ignore")

new = pd.Series(["a","b","c"])
name="val"
new.to_frame()

import matplotlib.pyplot as plt
student=["Ratan","vivek","Ravi","karan"]
Roll_No=[100,112,123,121]
student_series=pd.Series(student)
Roll_No_series=pd.Series(Roll_No)
frame={'student':student_series,'Roll_No':Roll_No_series}
result=pd.DataFrame(frame)
print(result)