# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CgXzuw0ZITihn3Cse_V1KQRgSpD1u0HB
"""

# create series from array
import pandas as pd
df=pd.DataFrame()
print(df)

info={"Roll_No":[100,102,103],"Branch":["CSE(AIML)","CSE(IOT)","CSE(DA)"]}
df=pd.DataFrame(info)
print(df)

info = {"one": pd.Series([1, 2, 3, 4, 5, 6]), "index": ['a', 'b', 'c', 'd', 'e','f'], 'two':pd.Series([1,2,3,4,5,6,7,8])
, "index": ['a', 'b', 'c', 'd', 'e','f','g','h']}
d1=pd.DataFrame(info)
print(df)

print(d1['one'])

print(df)
print("Add new column t an extisting dataFrame culomnn")
df["four"]=df["one"]+df["three"]
print(df)